name: DeathMessageCount
version: 2.1
main: me.nate.deathmessagecount.DeathMessageCount
api-version: 1.16
authors: [ Gk01234 ]
description: Adds a death counter to player death messages
commands:
  deaths:
    description: Tells you how many deaths you have
    usage: /deaths <player> or /d <player>
    aliases: d
